### ISSUE TITLE
wat

### ISSUE THREAD

**Issue by LouisRitchie** [williamgrosset/turtle#1]
![image](https://user-images.githubusercontent.com/10478031/36712970-342442de-1b40-11e8-8d7e-badb81b4a13d.png)

**Comment by LouisRitchie** [comment]
this looks like some cool stuff Will, I'll have to check it out

**Comment by williamgrosset** [comment]
![nice](https://user-images.githubusercontent.com/16131737/36953768-15dba4ac-1fd2-11e8-9c45-829a1f1499c6.png)
